version: "3"
   
services:
  cblti:
    build: .
    env_file:
      - 'settings.env'
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - './files/ssl:/etc/ssl/cblti'
      - '/var/run/docker.sock:/var/run/docker.sock'
      - content:/srv/www/lti/content/
      - processing:/opt/processing/
      - './files/cblti/process.sh:/opt/processing/process.sh'
  mysql:
    env_file:
      - 'settings.env'
    image: mysql
    environment:
      MYSQL_DATABASE: cblti
      MYSQL_USER: cblti
      MYSQL_RANDOM_ROOT_PASSWORD: 1
    volumes:
      - mysqldata:/var/lib/mysql
volumes: 
  mysqldata:
  content:
  processing:
